[supervisord]
logfile=logs/supervisord.log
logfile_maxbytes=50MB
logfile_backups=5
loglevel=info
pidfile=logs/supervisord.pid
nodaemon=false
minfds=1024
minprocs=200

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor_eset_soc.sock

[unix_http_server]
file=/tmp/supervisor_eset_soc.sock

[program:api]
command=.venv/bin/uvicorn src.main:app --host %(ENV_APP_HOST)s --port %(ENV_APP_PORT)s
directory=.
autostart=true
autorestart=true
stdout_logfile=logs/app.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile=logs/app.err.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=5
environment=APP_HOST="0.0.0.0",APP_PORT="8000"

[program:syslog_server]
command=.venv/bin/python -m syslog_server.server
directory=.
autostart=true
autorestart=true
stdout_logfile=logs/syslog_server.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile=logs/syslog_server.err.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=5
